language: python

# you can use Python 3.7 instead
python: "3.7"

# don't clone more than necessary
git:
  depth: 1

# Install any dependencies
install:
  - pip install -r requirements.txt
    
# script to run tests. Script can have many commands, one per line.
script: 
  - pip install coverage
  - coverage -m unittest discover -p "*_test.py"

after-script:
  - bash <(curl -s https://codecov.io/bash)